const defaultExercises = [
  {
    exerciseName: 'Russian Twist',
    exerciseCalories: '3',
    exerciseType: 'abs',
    exerciseImage: 'https://www.bodybuilding.com/images/2016/may/top-10-ab-splitting-exercises-v2-1-700xh.jpg',
    exerciseDescription: 'Động tác xoay người kiểu Nga có tải, thực hiện 10 lần mỗi bên. Giữ trọng lượng bằng cả hai tay để chống lại. Vặn thân sang bên phải cho đến khi cánh tay song song với sàn. Di chuyển trở lại vị trí bắt đầu và sau đó chuyển sang phía đối diện.',
  },
  {
    exerciseName: 'Reverse Crunch',
    exerciseCalories: '4',
    exerciseType: 'abs',
    exerciseImage: 'https://i.ytimg.com/vi/gAyTBB4lm3I/maxresdefault.jpg',
    exerciseDescription: 'Nằm ngửa trên sàn, đặt lòng bàn tay xuống sàn ở hai bên. Co chân thành 90 độ và đưa chân lên sao cho đùi vuông góc với sàn. Sử dụng cơ bụng, cong đầu gối về phía ngực cho đến khi mông nâng lên khỏi sàn rồi từ từ trở lại vị trí ban đầu. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát và kéo dài khoảng 3 giây, với chuyển động đi xuống không nhanh hơn chuyển động đi lên.',
  },
  {
    exerciseName: 'Hanging Knee Tocks',
    exerciseCalories: '3',
    exerciseType: 'abs',
    exerciseImage: 'https://www.getstrong.fit/images/Hanging%20Knee%20Tucks%20Variation.jpg',
    exerciseDescription: 'Bắt đầu bằng cách treo người từ một thanh nhúng với hai cánh tay hơi rộng hơn chiều rộng bằng vai và hai chân buông thõng thẳng xuống; nếu có, hãy sử dụng dây đai cánh tay để loại bỏ căng thẳng trên cánh tay của bạn. Nâng đầu gối của bạn cao nhất có thể vào ngực và sau đó hạ đầu gối trở lại vị trí bắt đầu; không cho phép cơ thể của bạn để lắc lư. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát, kéo dài khoảng 4 giây, với chuyển động đi xuống không nhanh hơn chuyển động đi lên.',
  },
  {
    exerciseName: 'leg Raises',
    exerciseCalories: '3',
    exerciseType: 'abs',
    exerciseImage: 'https://cdn2.coachmag.co.uk/sites/coachmag/files/2018/06/straight-leg-raise.jpg',
    exerciseDescription: 'Nằm trên đầu của một băng ghế phẳng hoặc sàn nhà và ổn định cơ thể bằng cách nắm chặt băng ghế trên đầu hoặc ấn mạnh lòng bàn tay xuống đất; mở rộng chân của bạn ra. Giữ chân ở tư thế cố định, hơi cong trong suốt động tác, nâng chân lên theo hình bán nguyệt cho đến khi chúng cao hơn mặt sàn khoảng 75 độ. Đảo ngược chuyển động và trở lại điểm xuất phát. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát, kéo dài khoảng 4 giây, với chuyển động đi xuống không nhanh hơn chuyển động đi lên.',
  },
  {
    exerciseName: 'Incline Sit-ups',
    exerciseCalories: '2',
    exerciseType: 'abs',
    exerciseImage: 'https://i.ytimg.com/vi/KaefUzFR35g/maxresdefault.jpg',
    exerciseDescription: 'Ngồi trên băng ghế nghiêng hoặc ván nghiêng bụng và đặt bàn chân của bạn dưới tấm đệm. Nằm ngửa trên băng ghế nghiêng, hai tay đặt ngang ngực hoặc đặt tay sau đầu. Cong phần trên cơ thể của bạn lên cho đến khi nó ở một góc nhỏ hơn 90 độ so với sàn nhà; Quay trở lại vị trí bắt đầu. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát và kéo dài khoảng 3 giây, với chuyển động đi xuống không nhanh hơn chuyển động đi lên.',
  },
  {
    exerciseName: 'Crunch Twists',
    exerciseCalories: '2',
    exerciseType: 'abs',
    exerciseImage: 'https://image.shutterstock.com/image-illustration/twist-crunch-pose-by-sports-260nw-1886507518.jpg',
    exerciseDescription: 'Nằm ngửa trên sàn, hai tay ôm sau tai và chống khuỷu tay ra ngoài. Bắt chéo mắt cá chân, đầu gối hơi cong và nâng cao chân cho đến khi đầu gối vuông góc với cơ thể. Đưa vai trái lên khỏi mặt đất khi bạn bắt chéo khuỷu tay trái qua đầu gối phải. Quay trở lại vị trí bắt đầu và lặp lại, bắt đầu với vai phải, bắt chéo khuỷu tay phải qua đầu gối trái.',
  },
  {
    exerciseName: 'Barbell Bench Press',
    exerciseCalories: '5',
    exerciseType: 'chest',
    exerciseImage: 'https://www.muscleandfitness.com/wp-content/uploads/2017/04/Bench-Press-Main-800800.jpg?w=800&h=630&crop=1&quality=86&strip=all',
    exerciseDescription: 'Nằm trên một băng ghế phẳng, chân chạm đất và vai của bạn cách băng ghế khoảng 3-4 inch so với tư thế đứng thẳng. Nắm thanh đòn rộng hơn khoảng 3-4 inch so với chiều rộng vai và đặt hai tay của bạn cách đều nhau bằng cách sử dụng các điểm đánh dấu trên thanh. Nâng thanh ra khỏi giá đến một điểm ngay trên khớp vai của bạn. Hạ thanh tạ xuống giữa ngực (Pectorals) với cánh tay trên của bạn di chuyển thẳng ra hai bên; chạm nhẹ vào ngực. Nhấn thanh lên vị trí bắt đầu; không khóa khuỷu tay của bạn ở trên cùng. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát và kéo dài khoảng 3 giây, với chuyển động đi xuống không nhanh hơn chuyển động đi lên. Không bật thanh tạ ra khỏi ngực và luôn giữ mông trên băng ghế.',
  },
  {
    exerciseName: 'Dumbbell Bench Press',
    exerciseCalories: '5',
    exerciseType: 'chest',
    exerciseImage: 'https://www.thethaothientruong.vn/uploads/contents/Dumbbell-Bench-Press.jpg',
    exerciseDescription: 'Ngồi trên đầu của một băng ghế phẳng với các quả tạ đặt trên đầu gối của bạn. Lăn cơ thể của bạn trở lại trên băng ghế, điều này sẽ giúp bạn có thể thoải mái di chuyển quả tạ đến một điểm ngay trên khớp vai của bạn (động tác này phải được đảo ngược lúc khi kết thúc bài tập, co đầu gối vào tạ rồi lăn lên tư thế ngồi). Bàn tay của bạn phải rộng hơn khoảng 3-4 inch so với chiều rộng của vai, với lòng bàn tay của bạn hướng về hướng của bàn chân của bạn. Hạ tạ xuống, với cánh tay trên của bạn di chuyển thẳng ra hai bên, đến mức thấp nhất có thể mà không gây khó chịu và đặt tay thẳng hàng với giữa ngực. Nhấn các quả tạ lên trên về phía giữa cơ thể của bạn. Không để các quả tạ chạm vào nhau và không khóa khuỷu tay của bạn ở phía trên. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát và kéo dài khoảng 3 giây, với chuyển động đi xuống không nhanh hơn chuyển động đi lên. Không sử dụng động tác bật nảy ở cuối động tác và luôn giữ mông trên băng ghế.',
  },
  {
    exerciseName: 'Incline Dumbbell Press',
    exerciseCalories: '4',
    exerciseType: 'chest',
    exerciseImage: 'https://hips.hearstapps.com/vidthumb/brightcove/5789411ce694aa370d8836c7/thumb_1468612894.png?crop=1xw%3A1xh%3Bcenter%2Ctop&resize=480%3A270',
    exerciseDescription: 'Ngồi trên ghế của một băng ghế nghiêng với các quả tạ đặt trên đầu gối của bạn. Đung đưa cơ thể của bạn trở lại trên băng ghế nghiêng, điều này sẽ giúp bạn có thể thoải mái di chuyển quả tạ đến một điểm ngay trên khớp vai của bạn (động tác này nên được đảo ngược khi kết thúc bài tập, với đầu gối của bạn kéo vào quả tạ và sau đó đung đưa lên đến một vị trí ngồi). Bàn tay của bạn phải rộng hơn khoảng 3-4 inch so với chiều rộng của vai, với lòng bàn tay của bạn hướng về hướng của bàn chân của bạn. Hạ tạ xuống, với cánh tay trên của bạn di chuyển thẳng ra hai bên, đến mức thấp nhất có thể mà không gây khó chịu và đặt tay thẳng hàng với giữa ngực. Nhấn các quả tạ về vị trí bắt đầu; không khóa khuỷu tay của bạn ở trên cùng. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát và kéo dài khoảng 3 giây, với chuyển động đi xuống không nhanh hơn chuyển động đi lên. Không sử dụng động tác bật nảy ở cuối động tác và luôn giữ mông trên băng ghế.',
  },
  {
    exerciseName: 'Incline Barbell Press',
    exerciseCalories: '4',
    exerciseType: 'chest',
    exerciseImage: 'https://image.shutterstock.com/image-illustration/press-bar-lying-on-incline-260nw-425668825.jpg',
    exerciseDescription: 'Nằm trên một băng ghế nghiêng với bàn chân của bạn trên sàn hoặc miếng đệm chân và hơi cong ở lưng dưới của bạn. Nắm thanh đòn rộng hơn khoảng 3-4 inch so với chiều rộng vai và đặt hai tay của bạn cách đều nhau bằng cách sử dụng các điểm đánh dấu trên thanh. Nâng thanh ra khỏi giá đến một điểm ngay trên khớp vai của bạn. Hạ thanh tạ xuống phần trên của ngực (Pectorals) với cánh tay trên của bạn di chuyển thẳng ra hai bên; chạm nhẹ vào ngực trên của bạn. Nhấn thanh lên vị trí bắt đầu; không khóa khuỷu tay của bạn ở trên cùng. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát và kéo dài khoảng 3 giây, với chuyển động đi xuống không nhanh hơn chuyển động đi lên. Không bật thanh tạ ra khỏi ngực và luôn giữ mông trên băng ghế.',
  },
  {
    exerciseName: 'Push Up',
    exerciseCalories: '4',
    exerciseType: 'chest',
    exerciseImage: 'https://lh3.googleusercontent.com/proxy/jbzMI_MrFYRfKgO6JHebpUe3fSuh-s9oTn92ZY7LY4Hh_c-qM9hr2yC6ve-3So7UKNr3K2BY2qHC2Mr94TFdcTahd-caOf9lOriEdN910q4J52-7tgp8eA',
    exerciseDescription: 'Nâng đỡ cơ thể bằng các quả bóng bằng chân và bằng tay. Đặt hai tay rộng hơn chiều rộng bằng vai một chút, lòng bàn tay đặt phẳng trên sàn. Duỗi thẳng cánh tay mà không khóa khuỷu tay. Hạ thấp thân người xuống cho đến khi ngực cách sàn một phần inch. Đẩy người trở lại vị trí ban đầu. BIẾN DẠNG 1 - Đẩy chân nâng cao - Tăng nhu cầu lên ngực trên bằng cách đặt cả hai chân lên băng ghế hoặc quả bóng Thụy Sĩ. BIẾN SỐ 2 - Chống đẩy T - Giữ một cặp tạ nhẹ với tay cầm ở vị trí trung tính và vào tư thế chống đẩy chuẩn, với tay đặt ngay dưới vai. Thực hiện một động tác đẩy cơ bản. Sau đó, giữ vị trí trên cùng và nâng quả tạ bằng tay không thuận về phía trần nhà trong khi xoay thân của bạn theo cùng một hướng để bạn quay mặt sang một bên. Nâng đỡ và giữ thăng bằng bằng cánh tay còn lại của bạn sao cho cánh tay và cơ thể tạo thành chữ T, với cánh tay vuông góc với sàn. Quay trở lại vị trí bắt đầu và lặp lại với cánh tay đối diện.',
  },
  {
    exerciseName: 'Machine chest Press',
    exerciseCalories: '4',
    exerciseType: 'chest',
    exerciseImage: 'https://lh3.googleusercontent.com/proxy/8fAlqoW5QEBrHLptallX6RMfIiaWJAZcVTpp_H6UI65mArvrQhUSmo5FErD8FeqD2AkzQnm2Bpm36z-MrZbRenItGFNBiQ',
    exerciseDescription: 'Điều chỉnh chiều cao ghế sao cho tay cầm ngang với tâm ngực của bạn. Giữ cánh tay trên vuông góc với thân, nhấn trọng lượng ra khỏi cơ thể, đảm bảo giữ cổ tay thẳng hàng với cẳng tay trong suốt chuyển động. Đảo ngược chuyển động và trở lại vị trí bắt đầu. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát, kéo dài khoảng 3 giây với chuyển động vào trong không nhanh hơn hướng ra ngoài. Giữ lưng của bạn bằng phẳng dựa vào đệm máy. Không khóa khuỷu tay của bạn ở đầu máy ép',
  },
  {
    exerciseName: 'Incline Machine chest Press',
    exerciseCalories: '4',
    exerciseType: 'chest',
    exerciseImage: 'https://www.jefit.com/images/exercises/800_600/713.jpg',
    exerciseDescription: 'Đặt ghế sao cho tay cầm sẽ hạ xuống ngay trước ngực của bạn. Ngồi với bàn chân của bạn trên sàn và hơi cong ở lưng dưới của bạn. Nắm tay cầm rộng hơn khoảng 3-4 inch so với chiều rộng vai. Nâng tay cầm lên một điểm ngay trên khớp vai của bạn. Hạ tay cầm xuống phần trên của ngực (Cơ ngực) với cánh tay trên của bạn di chuyển thẳng ra hai bên; chạm nhẹ vào ngực trên của bạn. Nhấn tay cầm lên vị trí bắt đầu; không khóa khuỷu tay của bạn ở trên cùng. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát và kéo dài khoảng 3 giây, với chuyển động đi xuống không nhanh hơn chuyển động đi lên.',
  },
  {
    exerciseName: 'Decline Barbell Bench Press',
    exerciseCalories: '4',
    exerciseType: 'chest',
    exerciseImage: 'https://i.pinimg.com/originals/4c/f1/48/4cf148ebd85967bce6410ccd2da17443.jpg',
    exerciseDescription: 'Nằm trên một băng ghế dài với bàn chân của bạn được móc vào dưới thanh hạn chế và hơi cong ở lưng thấp. Nắm thanh đòn rộng hơn khoảng 3-4 inch so với chiều rộng vai và đặt hai tay của bạn cách đều nhau bằng cách sử dụng các điểm đánh dấu trên thanh. Nâng thanh ra khỏi giá đến một điểm ngay trên khớp vai của bạn. Hạ thanh tạ xuống phần dưới của ngực (ngực) với cánh tay trên của bạn di chuyển thẳng ra hai bên; chạm nhẹ vào ngực dưới của bạn. Nhấn thanh lên vị trí bắt đầu; không khóa khuỷu tay của bạn ở trên cùng. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát và kéo dài khoảng 3 giây, với chuyển động đi xuống không nhanh hơn chuyển động đi lên. Không bật thanh tạ ra khỏi ngực và luôn giữ mông trên băng ghế.',
  },
  {
    exerciseName: 'Machine Wide Fly',
    exerciseCalories: '3',
    exerciseType: 'chest',
    exerciseImage: 'https://bodybuilding-wizard.com/wp-content/uploads/2014/12/machine-fly-exercise.jpg',
    exerciseDescription: 'Please be sure to use proper form',
  },
  {
    exerciseName: 'tricep Cable Pushdown',
    exerciseCalories: '2',
    exerciseType: 'tricep',
    exerciseImage: 'https://fitnessvolt.com/wp-content/uploads/2020/10/cable-triceps-pushdown-for-upper-arms-1024x536.jpg.webp',
    exerciseDescription: 'Gắn một thanh ngắn có góc nghiêng xuống từ giữa về cả hai đầu (thanh đẩy xuống) vào một ròng rọc phía trên. Đứng với hai bàn chân rộng bằng vai và hơi khuỵu gối cách thanh đẩy xuống khoảng 1 foot và hướng về phía chồng; duy trì đường cong tự nhiên ở lưng thấp của bạn trong suốt quá trình chuyển động. Nắm thanh tạ bằng hai tay cách nhau khoảng 4-6 inch, lòng bàn tay hướng xuống sàn và uốn cong khuỷu tay của bạn hơn 90 độ một chút. Đẩy thanh tạ xuống về phía sàn cho đến khi khuỷu tay của bạn thẳng, đảm bảo giữ chúng gần với hai bên của bạn; giữ cho thân của bạn bất động trong suốt quá trình chuyển động. Đảo ngược chuyển động và trở lại vị trí bắt đầu. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát và kéo dài khoảng 3 giây với chuyển động đi xuống không nhanh hơn chuyển động lên trên.',
  },
  {
    exerciseName: 'Machine tricep Extension',
    exerciseCalories: '2',
    exerciseType: 'tricep',
    exerciseImage: 'https://weighttraining.guide/wp-content/uploads/2018/11/Machine-triceps-extension-resized.png',
    exerciseDescription: 'Điều chỉnh độ cao của ghế sao cho phần sau của cánh tay của bạn nằm thẳng trên tấm đệm và khuỷu tay của bạn thẳng hàng với trục quay của máy; vai của bạn phải ở độ cao bằng với khuỷu tay. Điều chỉnh miếng đệm lưng sao cho lưng của bạn được hỗ trợ thoải mái ở tư thế thẳng đứng và nắm lấy tay cầm sao cho hai lòng bàn tay úp vào nhau với các ngón tay cái hướng về phía bạn. Nhấn tay cầm xuống và ra xa, giữ cho phần sau của cánh tay trên của bạn nằm trên tấm đệm, cho đến khi cánh tay của bạn thẳng. Đảo ngược chuyển động và trở lại vị trí bắt đầu. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát và kéo dài khoảng 3 giây với chuyển động đi xuống không nhanh hơn chuyển động lên trên.',
  },
  {
    exerciseName: 'One-arm Dumbbell Extension',
    exerciseCalories: '2',
    exerciseType: 'tricep',
    exerciseImage: 'https://cdn2.coachmag.co.uk/sites/coachmag/files/styles/insert_main_wide_image/public/2017/01/2-1b-triceps-extension.jpg?itok=HB8aC4c8',
    exerciseDescription: 'Ngồi trên cuối một băng ghế phẳng và nắm lấy quả tạ bằng tay phải. Nâng quả tạ ngay trên vai phải của bạn, với lòng bàn tay hướng về phía trước. Uốn cong cánh tay của bạn để quả tạ càng thấp càng tốt về phía sau bạn và gần đường giữa của cơ thể. Duỗi thẳng cánh tay phải của bạn; Cánh tay và thân trên bên phải của bạn phải bất động trong toàn bộ chuyển động. Duy trì đường cong tự nhiên của cột sống của bạn. Không cong lưng. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát và kéo dài khoảng 3 giây, với chuyển động xuống không nhanh hơn chuyển động lên. Sau khi hoàn thành đại diện của bạn cho một bên, đảo ngược các bên và lặp lại.',
  },
  {
    exerciseName: 'Lying tricep Extension',
    exerciseCalories: '3',
    exerciseType: 'tricep',
    exerciseImage: 'https://weighttraining.guide/wp-content/uploads/2017/08/lying-barbell-triceps-extension-resized.png',
    exerciseDescription: 'Nắm thanh tạ (có thể sử dụng tạ EZ-curl nếu thích) với hai tay cách nhau khoảng 6 inch. Ngồi trên cuối băng ghế với trọng lượng trên hai chân và lòng bàn tay úp xuống. Nâng thanh tạ lên ngang ngực và từ từ nằm lại trên băng ghế, đảm bảo duy trì các đường cong tự nhiên ở lưng trong suốt bài tập. Nhấn thẳng thanh tạ lên cho đến khi cánh tay của bạn duỗi thẳng lên trên người và vuông góc với sàn nhà; không khóa khuỷu tay của bạn. Hạ thanh tạ xuống theo đường vòng cung hình bán nguyệt đến trán của bạn, đảm bảo dừng đập vào trán trong khi giữ khuỷu tay của bạn hướng về phía trước. Nhấn thanh tạ lên để đảo ngược chuyển động và trở lại vị trí bắt đầu. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát và kéo dài khoảng 3 giây với chuyển động đi xuống không nhanh hơn chuyển động lên trên.',
  },
  {
    exerciseName: 'Lateral Dumbell Raises',
    exerciseCalories: '3',
    exerciseType: 'shoulder',
    exerciseImage: 'https://www.thethaothientruong.vn/uploads/contents/dumbbell-lateral-raise.jpg',
    exerciseDescription: 'Lấy hai quả tạ và đứng với hai bàn chân rộng bằng vai. Giữ các quả tạ khoảng 4-5 inch ở phía trước của đùi trên của bạn và với lòng bàn tay hướng vào nhau, ấn chúng vào nhau. Giữ khuỷu tay uốn cong khoảng 20 độ và lòng bàn tay úp xuống sàn trong suốt động tác, nâng tạ lên và ra hai bên, về phía trước cơ thể một chút và theo hình bán nguyệt, cho đến khi chúng ngang với vai. Giữ thân của bạn nằm yên trong toàn bộ chuyển động. Ở đầu chuyển động, nghiêng quả tạ để đầu trước thấp hơn đầu sau một chút; Quay trở lại vị trí bắt đầu. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát và kéo dài khoảng 3 giây, với chuyển động đi xuống không nhanh hơn chuyển động đi lên.',
  },
  {
    exerciseName: 'Seated Dumbbell Press',
    exerciseCalories: '4',
    exerciseType: 'shoulder',
    exerciseImage: 'https://lifestylegeeky.com/wp-content/uploads/2019/05/Seated_Dumbbell_Overhead_Press-1.jpg',
    exerciseDescription: 'Ngồi trên ghế hoặc băng ghế có tựa lưng và đặt các quả tạ lên đầu gối của bạn. Bắt đầu với tạ ở vị trí ngang cằm với lòng bàn tay hướng ra xa bạn và cẳng tay vuông góc với sàn. Nhấn các quả tạ lên theo đường thẳng hướng lên trần nhà cho đến khi cánh tay của bạn duỗi ra hoàn toàn. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát, kéo dài khoảng 3 giây, với chuyển động đi xuống không nhanh hơn chuyển động đi lên. Không khóa khuỷu tay của bạn ở đầu chuyển động và không nảy ở cuối chuyển động.',
  },
  {
    exerciseName: 'Machine shoulder Press',
    exerciseCalories: '3',
    exerciseType: 'shoulder',
    exerciseImage: 'http://s3.amazonaws.com/prod.skimble/assets/1444842/image_iphone.jpg',
    exerciseDescription: 'Điều chỉnh độ cao của ghế sao cho tay cầm ngang với cằm. Nhấn tay cầm lên trên đầu và giữ cổ tay thẳng hàng với cẳng tay trong suốt chuyển động. Đảo ngược chuyển động và trở lại vị trí bắt đầu. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát và kéo dài khoảng 3 giây với chuyển động đi xuống không nhanh hơn chuyển động lên trên. Giữ lưng của bạn bằng phẳng dựa vào đệm máy. Không khóa khuỷu tay của bạn ở đầu chuyển động.',
  },
  {
    exerciseName: 'Lateral Cable Raises',
    exerciseCalories: '3',
    exerciseType: 'shoulder',
    exerciseImage: 'https://fitnessvolt.com/wp-content/uploads/2018/04/cable-one-arm-lateral-raise-1.jpg',
    exerciseDescription: 'Gắn một tay cầm vòng vào cuối ròng rọc sàn; Bài tập này sẽ được thực hiện từng vai một. Với thân của bạn vuông góc với chồng, đứng bằng chân trái của bạn cách ròng rọc khoảng 1-2 feet và bàn chân của bạn cách nhau rộng bằng vai. Nắm lấy tay cầm vòng trong tay phải của bạn và để nó nằm yên ở giữa đùi phải của bạn. Giữ khuỷu tay uốn cong khoảng 20 độ và lòng bàn tay hướng xuống sàn trong suốt động tác, nhấc thẳng tay cầm sang một bên, phía trước cơ thể và theo hình vòng cung bán nguyệt, cho đến khi nó ngang với vai. Giữ thân của bạn nằm yên trong toàn bộ chuyển động. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát, kéo dài khoảng 4 giây, với chuyển động đi xuống không nhanh hơn chuyển động đi lên. Sau khi hoàn thành đại diện của bạn cho một bên, đảo ngược các bên và lặp lại.',
  },
  {
    exerciseName: 'Front Dumbbell Raises',
    exerciseCalories: '3',
    exerciseType: 'shoulder',
    exerciseImage: 'https://i.pinimg.com/474x/b5/ba/d3/b5bad3adc59c4588af8a6ab3b0bd335b.jpg',
    exerciseDescription: 'Lấy hai quả tạ và đứng với hai chân rộng bằng vai, đặt hai quả tạ ở mặt trước của đùi trên. Giữ khuỷu tay uốn cong khoảng 10-15 độ và lòng bàn tay úp xuống sàn trong suốt động tác, nâng quả tạ lên theo hình bán nguyệt, cho đến khi chúng ngang với vai trước vai của bạn. Giữ thân của bạn nằm yên trong toàn bộ chuyển động. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát, kéo dài khoảng 3 giây, với chuyển động đi xuống không nhanh hơn chuyển động lên',
  },
  {
    exerciseName: 'Standing Barbell Press',
    exerciseCalories: '5',
    exerciseType: 'shoulder',
    exerciseImage: 'https://shamdi.vn/wp-content/uploads/2018/09/barbell-military-press.png',
    exerciseDescription: 'Đứng với hai bàn chân rộng bằng vai và hơi uốn cong đầu gối và duy trì đường cong tự nhiên ở lưng thấp trong suốt quá trình chuyển động. Nắm thanh tạ với lòng bàn tay hướng ra xa bạn và vị trí tay của bạn trên thanh tạ phải sao cho cẳng tay của bạn vuông góc với thanh tạ; cách đều tay của bạn bằng cách sử dụng các dấu trên thanh. Nâng thanh đến một điểm ngay trên khớp vai của bạn. Hạ thanh tạ xuống gần mặt đến ngang cằm và ấn tạ trở lại vị trí ban đầu. Không khóa khuỷu tay của bạn ở đầu chuyển động và không nảy ở cuối chuyển động.',
  },
  {
    exerciseName: 'Reverse Rear Dumbbell Raises',
    exerciseCalories: '3',
    exerciseType: 'shoulder',
    exerciseImage: 'https://i.pinimg.com/originals/01/dd/39/01dd39d90414c47cc18b6196a4671810.png',
    exerciseDescription: '1. Ngồi ở phần cuối của một băng ghế phẳng, chân của bạn gần với cơ thể của bạn. 2. Cúi người và đặt thân của bạn dọc theo đùi sao cho thân của bạn song song với mặt đất. 3. Nắm lấy hai quả tạ và để cánh tay buông thõng bên dưới, hai lòng bàn tay hướng về phía sau và ngón tay cái hướng vào nhau. 4. Giữ khuỷu tay uốn cong khoảng 20 độ và giữ cánh tay trên vuông góc với thân trong suốt động tác. 5. Giữ yên thân mình, nâng tạ lên và ra ngoài theo hình vòng cung bán nguyệt cho đến khi ngang vai, sau đó giữ nguyên tư thế đó trong giây lát và quay trở lại vị trí ban đầu. 6. Toàn bộ chuyển động nên được thực hiện một cách trơn tru, có kiểm soát và kéo dài khoảng 3 giây, với chuyển động đi xuống không nhanh hơn chuyển động lên trên.',
  },
  {
    exerciseName: 'Barbell Shrugs',
    exerciseCalories: '3',
    exerciseType: 'shoulder',
    exerciseImage: 'https://www.thethaothientruong.vn/uploads/contents/barbell-shrug.jpg',
    exerciseDescription: 'Nắm thanh tạ rộng bằng vai với lòng bàn tay hướng về phía bạn. Nâng thanh tạ ra khỏi giá đỡ bằng cách uốn cong và duỗi thẳng chân của bạn; Đảm bảo duy trì tư thế cong lưng tốt và ngẩng cao đầu trong suốt bài tập (nếu thanh tạ nằm trên sàn, hãy sử dụng hình thức tương tự như mô tả cho bài Deadlifts để nâng thanh tạ lên vị trí ban đầu). Giữ thanh tạ ngang đùi trên, thả lỏng vai và sau đó nhún vai lên và ra sau hết mức có thể, cố gắng chạm tai vào vai; giữ vị trí trong giây lát và trở lại vị trí ban đầu. Giữ thân của bạn nằm yên và cánh tay của bạn thẳng trong suốt quá trình chuyển động. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát và kéo dài khoảng 3 giây, với chuyển động đi xuống không nhanh hơn chuyển động đi lên. Không cong lưng.',
  },
  {
    exerciseName: 'Wide-Grip Front PullDown',
    exerciseCalories: '4',
    exerciseType: 'back',
    exerciseImage: 'https://1.bp.blogspot.com/-LCyzxqSydA8/XOo80h1nWXI/AAAAAAAABMI/fEiolYmOBgkUVie3rroZhwYatzQruqTeQCLcBGAs/s1600/wide-grip-lat-pulldown.jpg',
    exerciseDescription: 'Điều chỉnh ghế hoặc miếng đệm sao cho nó nằm trên đùi dưới ngay trên đầu gối của bạn. Đứng lên và nắm lấy thanh tạ với tay nắm rộng hơn vai một chút với lòng bàn tay hướng ra xa bạn. Ngồi xuống với cánh tay của bạn mở rộng hoàn toàn và đùi của bạn bên dưới miếng đệm. Kéo tạ xuống trước đầu cho đến khi gần đến ngực, tập trung kéo cùi chỏ xuống phía sau khi thực hiện động tác. Giữ tư thế cong lưng và thân của bạn ở một vị trí thẳng đứng cố định trong suốt quá trình di chuyển. Đảo ngược chuyển động và trở lại vị trí bắt đầu. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát, kéo dài khoảng 3 giây, với chuyển động đi xuống không nhanh hơn chuyển động đi lên.',
  },
  {
    exerciseName: 'One-arm Dumbbell Bent-Over Rows',
    exerciseCalories: '4',
    exerciseType: 'back',
    exerciseImage: 'https://cdn-0.weighttraining.guide/wp-content/uploads/2016/10/bent-over-one-arm-dumbbell-row-resized.png',
    exerciseDescription: 'Đặt đầu gối, ống chân và bàn tay phải của bạn trên một băng ghế phẳng, với bàn tay cách đầu gối khoảng 1-2 feet. Đưa tay trái xuống và nắm lấy quả tạ. Kéo quả tạ lên phía bên của lồng ngực dưới của bạn, với cánh tay trên của bạn gần với thân của bạn. Đưa quả tạ trở lại vị trí ban đầu. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát và kéo dài khoảng 3 giây, với chuyển động đi xuống không nhanh hơn chuyển động đi lên. Giữ lưng thẳng hoặc ở độ cong tự nhiên trong suốt bài tập. Sau khi hoàn thành đại diện của bạn cho một bên, đảo ngược các bên và lặp lại.',
  },
  {
    exerciseName: 'Seated Cable Rows',
    exerciseCalories: '4',
    exerciseType: 'back',
    exerciseImage: 'https://www.thethaothientruong.vn/uploads/contents/seated-cable-row.jpg',
    exerciseDescription: 'Bắt đầu bài tập nghiêng người về phía trước, hai tay đưa ra trước đầu gối, lưng thẳng, đầu gối gập một góc 45 độ, động tác này được duy trì trong suốt động tác. Giữ cùi chỏ sát hai bên, kéo tay cầm vào bụng và ưỡn lưng khi kết thúc động tác. Đảo ngược chuyển động và trở lại vị trí bắt đầu. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát và kéo dài khoảng 3 giây, với chuyển động vào trong không nhanh hơn chuyển động ra ngoài.',
  },
  {
    exerciseName: 'Close-Grip PullDown',
    exerciseCalories: '4',
    exerciseType: 'back',
    exerciseImage: 'https://i.pinimg.com/originals/fd/be/e5/fdbee5d6944431082ef6566b6dd8077f.png',
    exerciseDescription: 'Điều chỉnh độ cao của ghế đến vị trí mà chân của bạn được cố định dưới bộ ổn định có đệm và gắn một thanh thẳng vào một ròng rọc phía trên. Đứng lên và nắm thanh tạ với lòng bàn tay hướng về phía cách nhau khoảng 4-6 inch. Duỗi thẳng tay và trở lại tư thế ngồi với chân khóa dưới tấm đệm. Vòm lưng của bạn, đảm bảo bạn duy trì vòm trong toàn bộ chuyển động. Kéo thanh tạ trước cổ đến một điểm ở phần trên của ngực, đảm bảo kéo khuỷu tay xuống và ra sau dọc theo hai bên. Từ từ đảo ngược chuyển động và trở lại vị trí bắt đầu. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát và kéo dài khoảng 3 giây, với chuyển động đi xuống không nhanh hơn chuyển động đi lên.',
  },
  {
    exerciseName: 'Pull Ups',
    exerciseCalories: '5',
    exerciseType: 'back',
    exerciseImage: 'https://ktv.vn/wp-content/uploads/2016/11/unassisted-pullup.jpg',
    exerciseDescription: 'Lòng bàn tay quay mặt ra xa, kéo cằm của bạn lên trên thanh',
  },
  {
    exerciseName: 'Chin Ups',
    exerciseCalories: '4',
    exerciseType: 'back',
    exerciseImage: 'https://www.aleanlife.com/wp-content/uploads/2021/04/chin-up-490x322.jpg',
    exerciseDescription: 'Nhảy lên và nắm chắc thanh chống cằm với lòng bàn tay hướng về phía bạn và hai tay rộng bằng vai (nếu cần, sử dụng một băng ghế hoặc một nông cụ khác để hỗ trợ nâng người lên thanh tạ). Bình tĩnh để cho cánh tay của bạn duỗi thẳng hoàn toàn, điều này sẽ giúp Latissimus Dorsi của bạn căng ra trước khi chuyển động. Gập chân thành góc 90 độ và bắt chéo mắt cá chân. Kéo người lên đến điểm mà cằm của bạn ở trên thanh chống cằm và cong lưng về phía trên cùng của chuyển động. Đảo ngược chuyển động và trở lại vị trí bắt đầu. Giữ căng cơ vai của bạn ở dưới cùng của chuyển động để tránh chấn thương cho khớp vai.',
  },
  {
    exerciseName: 'Bent-Over Barbell Rows',
    exerciseCalories: '4',
    exerciseType: 'back',
    exerciseImage: 'https://www.thethaothientruong.vn/uploads/contents/bent-over-barbell-row.jpg',
    exerciseDescription: 'Với tư thế cong lưng và chân cong, cúi gập người xuống và nắm thanh tạ rộng bằng vai, đảm bảo khoảng cách hai tay bằng nhau bằng cách sử dụng các điểm đánh dấu trên thanh. Duỗi thẳng chân đủ để nâng thanh tạ lên khỏi mặt đất; Cánh tay của bạn nên được mở rộng với độ uốn cong khoảng 10-20 độ ở khuỷu tay. Kéo thanh tạ lên giữa bụng, với cánh tay trên của bạn ở một góc 45 độ so với thân của bạn và duy trì một vị trí cố định với thân của bạn trong suốt động tác. Đưa thanh tạ trở lại vị trí ban đầu. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát và kéo dài khoảng 3 giây, với chuyển động đi xuống không nhanh hơn chuyển động đi lên.',
  },
  {
    exerciseName: 'T-Bar Rows',
    exerciseCalories: '4',
    exerciseType: 'back',
    exerciseImage: 'https://fitnessvolt.com/wp-content/uploads/2020/03/barbell-t-bar-rows.jpg',
    exerciseDescription: 'Nằm với mặt trước của thân trên tấm đệm và nắm tay cầm của T-Bar cho phép lòng bàn tay của bạn hướng vào nhau (Nếu thiết bị T-Bar của bạn không có giá đỡ thân, hãy duy trì tư thế cong ở lưng, chân của bạn hơi cong và thân của bạn ở trên một chút song song). Bạn nên định vị sao cho các đĩa đệm thẳng hàng với tâm ngực của bạn ở đầu chuyển động. Kéo T-Bar lên đến thân của bạn, đảm bảo giữ cho khuỷu tay của bạn gần với hai bên và duy trì một vị trí cố định với thân của bạn trong suốt quá trình chuyển động. Đảo ngược chuyển động và trở lại vị trí bắt đầu. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát và kéo dài khoảng 3 giây, với chuyển động đi xuống không nhanh hơn chuyển động đi lên.',
  },
  {
    exerciseName: 'Dumbbell Rows',
    exerciseCalories: '3',
    exerciseType: 'back',
    exerciseImage: 'https://cdn.muscleandstrength.com/sites/default/files/bent-over-dumbbell-row-1.jpg',
    exerciseDescription: 'Bắt đầu: Lấy một cặp tạ, uốn cong bằng hông (không làm tròn lưng dưới của bạn) và hạ thấp thân của bạn cho đến khi nó gần như song song với sàn nhà. Để các quả tạ treo ở độ dài cánh tay từ vai của bạn. Chuyển động: Không di chuyển thân của bạn, kéo các quả tạ lên trên bằng cách nâng cao cánh tay trên, uốn cong khuỷu tay và ép chặt hai bả vai vào nhau. Tạm dừng và hạ tạ trở lại vị trí ban đầu.',
  },
  {
    exerciseName: 'Standing Alternate Dumbbell Curls',
    exerciseCalories: '2',
    exerciseType: 'Bicep',
    exerciseImage: 'https://i.pinimg.com/originals/83/a5/0b/83a50b234b8032e64a50316ef5e102f9.png',
    exerciseDescription: 'Nắm chặt mỗi quả tạ bằng bàn tay của bạn ở giữa tay cầm với lòng bàn tay hướng về phía đùi của bạn. Đứng với hai bàn chân rộng bằng vai và hơi uốn cong đầu gối và duy trì đường cong tự nhiên ở lưng thấp trong suốt quá trình chuyển động. Cong quả tạ bên phải lên và đồng thời xoay bàn tay của bạn ra ngoài sao cho tại điểm giữa của chuyển động, lòng bàn tay của bạn hướng lên trần nhà và giữ nguyên tư thế tay đó trong phần còn lại của chuyển động. Kết thúc động tác khi quả tạ gần ngang với cằm. Giữ cho khuỷu tay và cánh tay trên của bạn cố định vào một bên của thân trong suốt chuyển động. Đảo ngược chuyển động và trở lại vị trí bắt đầu; lặp lại với cánh tay còn lại. Toàn bộ chuyển động cho mỗi cánh tay phải được thực hiện một cách trơn tru, có kiểm soát và kéo dài khoảng 3 giây với chuyển động xuống không nhanh hơn hướng lên.',
  },
  {
    exerciseName: 'Standing BarBell Curls',
    exerciseCalories: '2',
    exerciseType: 'Bicep',
    exerciseImage: 'https://cdn2.coachmag.co.uk/sites/coachmag/files/styles/insert_main_wide_image/public/2016/07/3-3a-barbell-bicpes-curl.jpg?itok=JoJ78E5m',
    exerciseDescription: 'Giữ thanh tạ dọc theo đùi trên của bạn với tay nắm rộng bằng vai và lòng bàn tay hướng về phía trước. Đứng với hai bàn chân rộng bằng vai và hơi uốn cong đầu gối và duy trì đường cong tự nhiên ở lưng thấp trong suốt quá trình chuyển động. Cong thanh tạ về phía ngực cho đến khi gần chạm cằm, đảm bảo giữ cho khuỷu tay và bắp tay của bạn cố định vào hai bên thân trong suốt động tác. Đảo ngược chuyển động và trở lại vị trí bắt đầu. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát và kéo dài khoảng 3 giây với chuyển động đi xuống không nhanh hơn chuyển động lên trên.',
  },
  {
    exerciseName: 'Cable Curls',
    exerciseCalories: '2',
    exerciseType: 'Bicep',
    exerciseImage: 'http://www.burnthefatinnercircle.com/members/images/1801.jpg',
    exerciseDescription: 'Gắn thanh thẳng vào đầu ròng rọc trên sàn và đứng cách chồng tạ khoảng 1-1 + feet. Giữ thanh dọc theo đùi trên của bạn với tay nắm rộng bằng vai và lòng bàn tay hướng về phía trước. Đứng hơi cong đầu gối trong khi vẫn giữ được đường cong tự nhiên ở lưng thấp. Cong thanh tạ về phía ngực cho đến khi gần chạm vào cằm, đảm bảo giữ cho khuỷu tay và bắp tay của bạn cố định vào hai bên thân trong suốt động tác. Đảo ngược chuyển động và trở lại vị trí bắt đầu. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát và kéo dài khoảng 3 giây với chuyển động đi xuống không nhanh hơn chuyển động lên trên.',
  },
  {
    exerciseName: 'Concentration Curls',
    exerciseCalories: '2',
    exerciseType: 'Bicep',
    exerciseImage: 'https://www.thethaothientruong.vn/uploads/contents/concentration-curls.jpg',
    exerciseDescription: 'Nắm chặt một quả tạ bằng tay phải ở giữa tay cầm và ngồi xuống cuối một băng ghế phẳng. Đặt mặt sau của bắp tay phải của bạn dựa vào phần bên trong của đùi phải xuống gần đầu gối, làm cho cẳng tay vuông góc với đùi và để cánh tay của bạn buông thõng thẳng. Với lòng bàn tay hướng thẳng ra khỏi đùi, cuộn quả tạ lên cho đến khi nó ngang với vai. Đảo ngược chuyển động và trở lại vị trí bắt đầu; lặp lại với cánh tay còn lại. Toàn bộ chuyển động cho mỗi cánh tay phải được thực hiện một cách trơn tru, có kiểm soát và kéo dài khoảng 3 giây với chuyển động xuống không nhanh hơn hướng lên.',
  },
  {
    exerciseName: 'Machine Preacher Curls',
    exerciseCalories: '2',
    exerciseType: 'Bicep',
    exerciseImage: 'https://i.pinimg.com/originals/fc/c0/b6/fcc0b6f40a3b2ec0ec9e09b7c8195465.png',
    exerciseDescription: 'Adjust the seat position so that the back portion of your arms lie flat on the pad and your elbows line up with the axis of rotation of the machine.\r\n \r\nGrab the handles in an underhand position with your palms facing up.\r\n \r\nPull your hands towards your face while keeping the back part of your arms flat on the pad until they are close to your chin.\r\n \r\nReverse the movement and return to the starting position; maintain a slight bend in the elbow to prevent joint locking at the end of the movement.\r\n \r\nThe entire motion should be performed in a smooth, controlled manner that lasts about 3 seconds with the downward movement no faster than the upward.',
  },
  {
    exerciseName: 'leg Press',
    exerciseCalories: '4',
    exerciseType: 'leg',
    exerciseImage: 'https://image.shutterstock.com/image-illustration/inclined-leg-press-3d-illustration-260nw-434632384.jpg',
    exerciseDescription: 'Điều chỉnh khe góc của tấm đệm mặt sau sao cho gần chính giữa nhất rồi đặt vào máy. Đặt bàn chân của bạn cách nhau khoảng 6-8 inch trên trung tâm của nền tảng và ngón chân của bạn hướng về phía trước theo góc tự nhiên của chúng và nắm lấy tay cầm bên cạnh hông của bạn. Với lưng tựa tốt, nhấn trọng lượng lên và thả các khóa trên máy. Hạ tạ xuống cho đến khi đầu gối của bạn ở một góc 90 độ, đảm bảo giữ hông xuống ghế, lưng cong và đầu gối hướng ra ngoài cùng chiều với bàn chân trong suốt động tác. Giữ cho phần dưới bàn chân tiếp xúc hoàn toàn với nền tảng, nhưng tinh thần tập trung vào việc đẩy trọng lượng lên qua gót chân của bạn. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát, kéo dài khoảng 4 giây, với chuyển động đi xuống không nhanh hơn chuyển động đi lên. Không nảy ở dưới cùng của chuyển động và không bao giờ khóa đầu gối của bạn ở trên cùng. Tập trung tâm trí vào cơ đùi. Cảm thấy mình đang đẩy qua gót chân của bạn.',
  },
  {
    exerciseName: 'leg Extensions',
    exerciseCalories: '3',
    exerciseType: 'leg',
    exerciseImage: 'https://www.thethaothientruong.vn/uploads/contents/leg-extension.jpg',
    exerciseDescription: 'Điều chỉnh vị trí ghế sao cho khớp gối của bạn thẳng hàng với trục quay của máy và nắm lấy tay cầm gần hông. Móc bàn chân của bạn dưới miếng đệm chân để miếng đệm nằm ở phía trước mắt cá chân của bạn. Mở rộng bàn chân của bạn lên cho đến khi chân bạn thẳng, đảm bảo giữ mông của bạn xuống ghế trong suốt quá trình chuyển động. Đảo ngược chuyển động và trở lại vị trí bắt đầu. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát và kéo dài khoảng 3 giây với chuyển động đi xuống không nhanh hơn chuyển động lên trên. Giữ lưng của bạn bằng phẳng dựa vào đệm máy',
  },
  {
    exerciseName: 'Dumbbell Lunges',
    exerciseCalories: '5',
    exerciseType: 'leg',
    exerciseImage: 'https://i.pinimg.com/originals/b8/d5/83/b8d58357b3f86b04673caa8251dc34e1.png',
    exerciseDescription: 'Giữ tạ ở hai bên với cánh tay của bạn thẳng. Với bàn chân của bạn cách nhau khoảng 8 inch và các ngón chân hướng thẳng về phía trước, bước về phía trước khoảng 2-2 + bàn chân bằng chân phải của bạn. Gập chân phải và hạ thấp cơ thể cho đến khi đầu gối trái cách mặt đất khoảng 3-4 inch, giữ đường cong tự nhiên của cột sống bằng cách căng cơ bụng và lưng dưới; đầu gối phải của bạn phải ở phía trước mắt cá chân phải khoảng 3-4 inch. Duỗi thẳng chân phải của bạn và trở lại vị trí bắt đầu; lặp lại với chân đối diện. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát, kéo dài khoảng 4 giây, với chuyển động đi xuống không nhanh hơn chuyển động đi lên.',
  },
  {
    exerciseName: 'Barbell Squats',
    exerciseCalories: '4',
    exerciseType: 'leg',
    exerciseImage: 'https://weighttraining.guide/wp-content/uploads/2016/10/barbell-squat-resized.png',
    exerciseDescription: 'Đặt cơ thể của bạn trên giá ngồi xổm sao cho thanh tạ nằm sau đầu trên vai và hình thang, không nằm trên cổ của bạn. Khuỵu gối một chút và nắm chặt thanh xà một cách thoải mái. Duỗi thẳng chân để nâng thanh tạ lên rồi lùi lại một bước. Đứng với hai bàn chân rộng bằng vai với các ngón chân hướng về phía trước theo góc tự nhiên. Duy trì đường cong tự nhiên của cột sống bằng cách căng cơ bụng và lưng dưới. Ngẩng đầu, nhìn về phía trước trong suốt bài tập. Ngồi xổm xuống cho đến khi đùi của bạn ở dưới một chút song song với sàn, đảm bảo giữ cho thân của bạn cố định ở vị trí thẳng nhất có thể trong suốt quá trình chuyển động và đầu gối của bạn di chuyển ra ngoài cùng hướng với bàn chân của bạn. Đảo ngược chuyển động và trở lại vị trí bắt đầu. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát, kéo dài khoảng 4 giây, với chuyển động đi xuống không nhanh hơn chuyển động đi lên. Không nảy ở dưới cùng của chuyển động và không bao giờ khóa đầu gối của bạn ở trên cùng.',
  },
  {
    exerciseName: 'Hack Squats',
    exerciseCalories: '4',
    exerciseType: 'leg',
    exerciseImage: 'https://image.shutterstock.com/image-illustration/hack-squats-3d-illustration-260nw-421042363.jpg',
    exerciseDescription: 'Đặt lưng của bạn trên tấm đệm trượt, đặt bàn chân của bạn cách nhau khoảng 6-8 inch trên trung tâm của nền tảng và các ngón chân của bạn hướng về phía trước theo góc tự nhiên của chúng; đặt tay của bạn trên tay cầm nằm phía trên vai của bạn. Duỗi thẳng chân, mở chốt an toàn rồi hơi co chân lại; Giữ tư thế cong ở lưng thấp, đồng thời căng cơ lưng và cơ bụng trong suốt quá trình chuyển động. Ngồi xổm xuống cho đến khi đùi của bạn ở dưới một chút song song với sàn, đảm bảo giữ cho đầu gối của bạn di chuyển ra ngoài cùng hướng với bàn chân của bạn. Đảo ngược chuyển động và trở lại vị trí bắt đầu. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát, kéo dài khoảng 4 giây, với chuyển động đi xuống không nhanh hơn chuyển động đi lên. Không nảy ở dưới cùng của chuyển động và không bao giờ khóa đầu gối của bạn ở trên cùng.',
  },
  {
    exerciseName: 'Deadlift',
    exerciseCalories: '5',
    exerciseType: 'leg',
    exerciseImage: 'https://sasukegym.vn/wp-content/uploads/2019/09/Deadlift.jpg',
    exerciseDescription: 'Nắm thanh tạ rộng bằng vai với cách cầm lòng bàn tay xen kẽ (một lòng bàn tay hướng lên trên và lòng bàn tay còn lại hướng xuống). Bàn chân của bạn phải cách nhau rộng bằng vai và đầu gối của bạn phải được uốn cong ở vị trí bắt đầu. Lưng dưới và lưng trên của bạn phải giữ thẳng và ngẩng cao đầu trong suốt quá trình chuyển động. Bắt đầu bằng cách ưỡn ngực về phía trước để căn thẳng lưng. Duỗi thẳng chân và sau đó dựng thẳng thân lên, như thể bạn đang đứng lên khỏi ghế; bạn nên kết thúc động tác ở tư thế đứng, ngực ưỡn ra. Trở lại vị trí ban đầu bằng cách từ từ hạ tạ xuống đất. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát và kéo dài khoảng 4 giây, với chuyển động đi xuống không nhanh hơn chuyển động đi lên.',
  },
  {
    exerciseName: 'Sumo Deadlift',
    exerciseCalories: '5',
    exerciseType: 'leg',
    exerciseImage: 'https://bizweb.dktcdn.net/100/333/136/files/sumo-deadlift.png?v=1563276278193',
    exerciseDescription: 'Đứng trên thanh tạ với hai chân dang rộng và bàn chân chếch ra ngoài 45 độ. Thanh tạ phải ở ngay sát chân dưới của bạn. Ngồi xổm xuống và nắm lấy thanh tạ bằng tay, với cánh tay của bạn ở trong chân của bạn. Bắt đầu với thân của bạn càng thẳng càng tốt, hông ra sau, lưng phẳng, bả vai kéo vào nhau và cánh tay thẳng. Đẩy hông về phía trước và đứng với thanh tạ.',
  },
  {
    exerciseName: 'Standing Calf Raises',
    exerciseCalories: '2',
    exerciseType: 'leg',
    exerciseImage: 'http://s3.amazonaws.com/prod.skimble/assets/819768/image_iphone.jpg',
    exerciseDescription: 'Đặt vai của bạn trực tiếp dưới tấm đệm với các quả bóng của bàn chân của bạn trên bệ bàn chân cách nhau khoảng 6-8 inch. Trong khi thực hiện động tác, bạn nên đứng thẳng hoàn toàn với chuyển động duy nhất xảy ra ở khớp mắt cá chân của bạn. Giữ chân thẳng, hạ gót chân xuống cho đến khi bạn cảm thấy bắp chân căng ra. Nâng cơ thể lên cao hết mức có thể bằng các ngón chân, giữ nguyên ở đó một lúc rồi trở lại vị trí ban đầu. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát, kéo dài khoảng 3 giây, với chuyển động đi xuống không nhanh hơn chuyển động đi lên.',
  },
  {
    exerciseName: 'Lying leg Curl',
    exerciseCalories: '3',
    exerciseType: 'leg ',
    exerciseImage: 'https://weighttraining.guide/wp-content/uploads/2016/10/lying-leg-curl-resized.png',
    exerciseDescription: 'Nằm úp mặt trên băng ghế đảm bảo khớp gối thẳng hàng với trục quay của máy và nắm lấy tay cầm ở cuối băng ghế. Điều chỉnh miếng đệm chân sao cho nó nằm thoải mái ở cổ chân của bạn. Kéo bàn chân của bạn về phía mông, đảm bảo tránh chuyển động hông quá mức trong suốt quá trình chuyển động, cho đến khi chân của bạn vuông góc với trần nhà. Duy trì đường cong tự nhiên của cột sống bằng cách căng cơ bụng và lưng dưới. Ngẩng đầu, nhìn về phía trước trong suốt bài tập. Đảo ngược chuyển động và trở lại vị trí bắt đầu. Toàn bộ chuyển động phải được thực hiện một cách trơn tru, có kiểm soát và kéo dài khoảng 3 giây với chuyển động đi xuống không nhanh hơn chuyển động lên trên.',
  },
];
